spring:
  application:
    name: sopkathon-server-ios3
  profiles:
    default: local

server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /api/v1
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    try-it-out-enabled: true
